// constants/icons.js or assets/icons.js

const icons = {
  add: require('../assets/icons/add.png'),
  address: require('../assets/icons/address.png'),
  apple: require('../assets/icons/apple.png'),
  arrowBack: require('../assets/icons/arrow_back.png'),
  arrowBackCopy: require('../assets/icons/arrow_back copy.png'),
  at: require('../assets/icons/at.png'),
  calendar: require('../assets/icons/calendar.png'),
  callAttend: require('../assets/icons/call_attend.png'),
  callCut: require('../assets/icons/call_cut.png'),
  call: require('../assets/icons/call.png'),
  cancel: require('../assets/icons/cancel.png'),
  carRental: require('../assets/icons/Car Rental.png'),
  car: require('../assets/icons/car.png'),
  cashIcon: require('../assets/icons/cash_icon.png'),
  creditCard: require('../assets/icons/credit_card.png'),
  customerSupport: require('../assets/icons/customer-support.png'),
  customer: require('../assets/icons/customer.png'),
  delete: require('../assets/icons/delete.png'),
  dt: require('../assets/icons/dt.png'),
  edit: require('../assets/icons/edit.png'),
  et: require('../assets/icons/et.png'),
  exp: require('../assets/icons/exp.png'),
  facebook: require('../assets/icons/facebook.png'),
  ft: require('../assets/icons/ft.png'),
  g: require('../assets/icons/g.png'),
  google: require('../assets/icons/google.png'),
  greenArrow: require('../assets/icons/green_arrow.png'),
  group: require('../assets/icons/Group.png'),
  insta: require('../assets/icons/insta.png'),
  locationIcon: require('../assets/icons/location_icon.png'),
  logout: require('../assets/icons/logout.png'),
  marker: require('../assets/icons/marker.png'),
  momo: require('../assets/icons/momo.png'),
  msgGroup: require('../assets/icons/msg_group.png'),
  msgSend: require('../assets/icons/msg_send.png'),
  msg: require('../assets/icons/msg.png'),
  notificationSettings: require('../assets/icons/notification_settings.png'),
  orangeMoney: require('../assets/icons/orange_money.png'),
  password: require('../assets/icons/password.png'),
  paymentSuccess: require('../assets/icons/payment_successful_icon.png'),
  pencilEdit: require('../assets/icons/pencil-edit-02 (1).png'),
  profileIcon: require('../assets/icons/profile_icon.png'),
  ratting: require('../assets/icons/ratting.png'),
  redArrow: require('../assets/icons/red_arrow.png'),
  reviews: require('../assets/icons/reviews.png'),
  settings: require('../assets/icons/settings.png'),
  success: require('../assets/icons/success.png'),
  tickCircle: require('../assets/icons/tick-circle.png'),
  track: require('../assets/icons/track.png'),
  trips: require('../assets/icons/trips.png'),
  www: require('../assets/icons/www.png'),
  x: require('../assets/icons/x.png'),
  car3: require('../assets/icons/car3.png'),
  car1: require('../assets/icons/car1.png'),
  dollarsign: require('../assets/icons/dollarsign.png'),
};

export default icons;
